@startuml

class Repository << (S,#FF7700) Singleton >>
class Repository
    note right: Dependency Injection \n using Dagger2

package Database <<Database>> {
}

MainActivity  --*  MainFragment : contains
MainActivity  --*  ReportFragment : contains
ReportFragment --* ReportViewModel :  contains
ReportFragment <.. ReportViewModel :  LiveData
MainFragment --* MainViewModel : contains
MainFragment <.. MainViewModel : LiveData
ReportViewModel --* Repository : contains
MainViewModel --* Repository : contains
Repository --* LocalStorage : contains
LocalStorage --> Database: room

@enduml